// Generated by CoffeeScript 1.10.0
var CallbackCounter;

CallbackCounter = (function() {
  function CallbackCounter(count1, done) {
    this.count = count1;
    this.done = done;
    if (typeof count === 'function') {
      this.done = count;
      this.count = 0;
    }
    this.results = [];
  }

  CallbackCounter.prototype.incr = function(n) {
    return this.count += n || 1;
  };

  CallbackCounter.prototype.decr = function() {
    if (this.count <= 0) {
      throw new Error('count is negative');
    }
    this.count -= 1;
    if (this.count === 0) {
      return this.done();
    }
  };

  return CallbackCounter;

})();
