// Generated by CoffeeScript 1.10.0
var React, _,
  slice = [].slice;

React = require('react');

_ = require('underscore');

module.exports = {
  classFactory: function(spec) {
    var c;
    c = React.createClass(spec);
    return function() {
      var attrs, children;
      attrs = arguments[0], children = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return React.createElement(c, attrs, children);
    };
  },
  withKeys: function(arr) {
    return _.map(arr, function(elem, index) {
      if (elem.key === null) {
        return React.cloneElement(elem, {
          key: index
        });
      } else {
        return elem;
      }
    });
  },
  group: function(args) {
    var elem, index;
    return React.DOM.span({}, (function() {
      var ref, results;
      ref = _.flatten(args);
      results = [];
      for (index in ref) {
        elem = ref[index];
        if (elem.key === null) {
          results.push(React.cloneElement(elem, {
            key: index
          }));
        } else {
          results.push(elem);
        }
      }
      return results;
    })());
  }
};
